# See http://about.travis-ci.org/docs/user/build-configuration/
script:
  - sudo rm /etc/mavenrc
  - export MAVEN_OPTS="-Xmx2469m -XX:MaxPermSize=512m"
  - mvn -B -l /tmp/build.out clean install -T2 

after_failure: "tail -n 1000 /tmp/build.out"
